// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/JunLang-7/sduzg-alumin-platform/server/internal/model"
)

func newHistoryEntry(db *gorm.DB, opts ...gen.DOOption) historyEntry {
	_historyEntry := historyEntry{}

	_historyEntry.historyEntryDo.UseDB(db, opts...)
	_historyEntry.historyEntryDo.UseModel(&model.HistoryEntry{})

	tableName := _historyEntry.historyEntryDo.TableName()
	_historyEntry.ALL = field.NewAsterisk(tableName)
	_historyEntry.ID = field.NewUint64(tableName, "id")
	_historyEntry.Title = field.NewString(tableName, "title")
	_historyEntry.Summary = field.NewString(tableName, "summary")
	_historyEntry.Content = field.NewString(tableName, "content")
	_historyEntry.Status = field.NewString(tableName, "status")
	_historyEntry.CurrentVersion = field.NewUint32(tableName, "current_version")
	_historyEntry.CreatedBy = field.NewUint64(tableName, "created_by")
	_historyEntry.UpdatedBy = field.NewUint64(tableName, "updated_by")
	_historyEntry.CreatedAt = field.NewTime(tableName, "created_at")
	_historyEntry.UpdatedAt = field.NewTime(tableName, "updated_at")
	_historyEntry.DeletedAt = field.NewField(tableName, "deleted_at")

	_historyEntry.fillFieldMap()

	return _historyEntry
}

// historyEntry ?????????
type historyEntry struct {
	historyEntryDo historyEntryDo

	ALL            field.Asterisk
	ID             field.Uint64
	Title          field.String
	Summary        field.String
	Content        field.String
	Status         field.String // published / archived
	CurrentVersion field.Uint32
	CreatedBy      field.Uint64
	UpdatedBy      field.Uint64
	CreatedAt      field.Time
	UpdatedAt      field.Time
	DeletedAt      field.Field

	fieldMap map[string]field.Expr
}

func (h historyEntry) Table(newTableName string) *historyEntry {
	h.historyEntryDo.UseTable(newTableName)
	return h.updateTableName(newTableName)
}

func (h historyEntry) As(alias string) *historyEntry {
	h.historyEntryDo.DO = *(h.historyEntryDo.As(alias).(*gen.DO))
	return h.updateTableName(alias)
}

func (h *historyEntry) updateTableName(table string) *historyEntry {
	h.ALL = field.NewAsterisk(table)
	h.ID = field.NewUint64(table, "id")
	h.Title = field.NewString(table, "title")
	h.Summary = field.NewString(table, "summary")
	h.Content = field.NewString(table, "content")
	h.Status = field.NewString(table, "status")
	h.CurrentVersion = field.NewUint32(table, "current_version")
	h.CreatedBy = field.NewUint64(table, "created_by")
	h.UpdatedBy = field.NewUint64(table, "updated_by")
	h.CreatedAt = field.NewTime(table, "created_at")
	h.UpdatedAt = field.NewTime(table, "updated_at")
	h.DeletedAt = field.NewField(table, "deleted_at")

	h.fillFieldMap()

	return h
}

func (h *historyEntry) WithContext(ctx context.Context) *historyEntryDo {
	return h.historyEntryDo.WithContext(ctx)
}

func (h historyEntry) TableName() string { return h.historyEntryDo.TableName() }

func (h historyEntry) Alias() string { return h.historyEntryDo.Alias() }

func (h historyEntry) Columns(cols ...field.Expr) gen.Columns {
	return h.historyEntryDo.Columns(cols...)
}

func (h *historyEntry) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := h.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (h *historyEntry) fillFieldMap() {
	h.fieldMap = make(map[string]field.Expr, 11)
	h.fieldMap["id"] = h.ID
	h.fieldMap["title"] = h.Title
	h.fieldMap["summary"] = h.Summary
	h.fieldMap["content"] = h.Content
	h.fieldMap["status"] = h.Status
	h.fieldMap["current_version"] = h.CurrentVersion
	h.fieldMap["created_by"] = h.CreatedBy
	h.fieldMap["updated_by"] = h.UpdatedBy
	h.fieldMap["created_at"] = h.CreatedAt
	h.fieldMap["updated_at"] = h.UpdatedAt
	h.fieldMap["deleted_at"] = h.DeletedAt
}

func (h historyEntry) clone(db *gorm.DB) historyEntry {
	h.historyEntryDo.ReplaceConnPool(db.Statement.ConnPool)
	return h
}

func (h historyEntry) replaceDB(db *gorm.DB) historyEntry {
	h.historyEntryDo.ReplaceDB(db)
	return h
}

type historyEntryDo struct{ gen.DO }

func (h historyEntryDo) Debug() *historyEntryDo {
	return h.withDO(h.DO.Debug())
}

func (h historyEntryDo) WithContext(ctx context.Context) *historyEntryDo {
	return h.withDO(h.DO.WithContext(ctx))
}

func (h historyEntryDo) ReadDB() *historyEntryDo {
	return h.Clauses(dbresolver.Read)
}

func (h historyEntryDo) WriteDB() *historyEntryDo {
	return h.Clauses(dbresolver.Write)
}

func (h historyEntryDo) Session(config *gorm.Session) *historyEntryDo {
	return h.withDO(h.DO.Session(config))
}

func (h historyEntryDo) Clauses(conds ...clause.Expression) *historyEntryDo {
	return h.withDO(h.DO.Clauses(conds...))
}

func (h historyEntryDo) Returning(value interface{}, columns ...string) *historyEntryDo {
	return h.withDO(h.DO.Returning(value, columns...))
}

func (h historyEntryDo) Not(conds ...gen.Condition) *historyEntryDo {
	return h.withDO(h.DO.Not(conds...))
}

func (h historyEntryDo) Or(conds ...gen.Condition) *historyEntryDo {
	return h.withDO(h.DO.Or(conds...))
}

func (h historyEntryDo) Select(conds ...field.Expr) *historyEntryDo {
	return h.withDO(h.DO.Select(conds...))
}

func (h historyEntryDo) Where(conds ...gen.Condition) *historyEntryDo {
	return h.withDO(h.DO.Where(conds...))
}

func (h historyEntryDo) Order(conds ...field.Expr) *historyEntryDo {
	return h.withDO(h.DO.Order(conds...))
}

func (h historyEntryDo) Distinct(cols ...field.Expr) *historyEntryDo {
	return h.withDO(h.DO.Distinct(cols...))
}

func (h historyEntryDo) Omit(cols ...field.Expr) *historyEntryDo {
	return h.withDO(h.DO.Omit(cols...))
}

func (h historyEntryDo) Join(table schema.Tabler, on ...field.Expr) *historyEntryDo {
	return h.withDO(h.DO.Join(table, on...))
}

func (h historyEntryDo) LeftJoin(table schema.Tabler, on ...field.Expr) *historyEntryDo {
	return h.withDO(h.DO.LeftJoin(table, on...))
}

func (h historyEntryDo) RightJoin(table schema.Tabler, on ...field.Expr) *historyEntryDo {
	return h.withDO(h.DO.RightJoin(table, on...))
}

func (h historyEntryDo) Group(cols ...field.Expr) *historyEntryDo {
	return h.withDO(h.DO.Group(cols...))
}

func (h historyEntryDo) Having(conds ...gen.Condition) *historyEntryDo {
	return h.withDO(h.DO.Having(conds...))
}

func (h historyEntryDo) Limit(limit int) *historyEntryDo {
	return h.withDO(h.DO.Limit(limit))
}

func (h historyEntryDo) Offset(offset int) *historyEntryDo {
	return h.withDO(h.DO.Offset(offset))
}

func (h historyEntryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *historyEntryDo {
	return h.withDO(h.DO.Scopes(funcs...))
}

func (h historyEntryDo) Unscoped() *historyEntryDo {
	return h.withDO(h.DO.Unscoped())
}

func (h historyEntryDo) Create(values ...*model.HistoryEntry) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Create(values)
}

func (h historyEntryDo) CreateInBatches(values []*model.HistoryEntry, batchSize int) error {
	return h.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (h historyEntryDo) Save(values ...*model.HistoryEntry) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Save(values)
}

func (h historyEntryDo) First() (*model.HistoryEntry, error) {
	if result, err := h.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.HistoryEntry), nil
	}
}

func (h historyEntryDo) Take() (*model.HistoryEntry, error) {
	if result, err := h.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.HistoryEntry), nil
	}
}

func (h historyEntryDo) Last() (*model.HistoryEntry, error) {
	if result, err := h.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.HistoryEntry), nil
	}
}

func (h historyEntryDo) Find() ([]*model.HistoryEntry, error) {
	result, err := h.DO.Find()
	return result.([]*model.HistoryEntry), err
}

func (h historyEntryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.HistoryEntry, err error) {
	buf := make([]*model.HistoryEntry, 0, batchSize)
	err = h.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (h historyEntryDo) FindInBatches(result *[]*model.HistoryEntry, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return h.DO.FindInBatches(result, batchSize, fc)
}

func (h historyEntryDo) Attrs(attrs ...field.AssignExpr) *historyEntryDo {
	return h.withDO(h.DO.Attrs(attrs...))
}

func (h historyEntryDo) Assign(attrs ...field.AssignExpr) *historyEntryDo {
	return h.withDO(h.DO.Assign(attrs...))
}

func (h historyEntryDo) Joins(fields ...field.RelationField) *historyEntryDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Joins(_f))
	}
	return &h
}

func (h historyEntryDo) Preload(fields ...field.RelationField) *historyEntryDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Preload(_f))
	}
	return &h
}

func (h historyEntryDo) FirstOrInit() (*model.HistoryEntry, error) {
	if result, err := h.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.HistoryEntry), nil
	}
}

func (h historyEntryDo) FirstOrCreate() (*model.HistoryEntry, error) {
	if result, err := h.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.HistoryEntry), nil
	}
}

func (h historyEntryDo) FindByPage(offset int, limit int) (result []*model.HistoryEntry, count int64, err error) {
	result, err = h.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = h.Offset(-1).Limit(-1).Count()
	return
}

func (h historyEntryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = h.Count()
	if err != nil {
		return
	}

	err = h.Offset(offset).Limit(limit).Scan(result)
	return
}

func (h historyEntryDo) Scan(result interface{}) (err error) {
	return h.DO.Scan(result)
}

func (h historyEntryDo) Delete(models ...*model.HistoryEntry) (result gen.ResultInfo, err error) {
	return h.DO.Delete(models)
}

func (h *historyEntryDo) withDO(do gen.Dao) *historyEntryDo {
	h.DO = *do.(*gen.DO)
	return h
}
