// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/JunLang-7/sduzg-alumin-platform/server/internal/model"
)

func newHistoryContribution(db *gorm.DB, opts ...gen.DOOption) historyContribution {
	_historyContribution := historyContribution{}

	_historyContribution.historyContributionDo.UseDB(db, opts...)
	_historyContribution.historyContributionDo.UseModel(&model.HistoryContribution{})

	tableName := _historyContribution.historyContributionDo.TableName()
	_historyContribution.ALL = field.NewAsterisk(tableName)
	_historyContribution.ID = field.NewUint64(tableName, "id")
	_historyContribution.EntryID = field.NewUint64(tableName, "entry_id")
	_historyContribution.Title = field.NewString(tableName, "title")
	_historyContribution.SectionName = field.NewString(tableName, "section_name")
	_historyContribution.Content = field.NewString(tableName, "content")
	_historyContribution.SourceNote = field.NewString(tableName, "source_note")
	_historyContribution.ChangeNote = field.NewString(tableName, "change_note")
	_historyContribution.Status = field.NewString(tableName, "status")
	_historyContribution.DataDomainID = field.NewUint64(tableName, "data_domain_id")
	_historyContribution.AuthorUserID = field.NewUint64(tableName, "author_user_id")
	_historyContribution.AuthorAlumniID = field.NewUint64(tableName, "author_alumni_id")
	_historyContribution.ReviewedBy = field.NewUint64(tableName, "reviewed_by")
	_historyContribution.ReviewComment = field.NewString(tableName, "review_comment")
	_historyContribution.SubmittedAt = field.NewTime(tableName, "submitted_at")
	_historyContribution.ReviewedAt = field.NewTime(tableName, "reviewed_at")
	_historyContribution.CreatedAt = field.NewTime(tableName, "created_at")
	_historyContribution.UpdatedAt = field.NewTime(tableName, "updated_at")
	_historyContribution.DeletedAt = field.NewField(tableName, "deleted_at")

	_historyContribution.fillFieldMap()

	return _historyContribution
}

// historyContribution 院史校友投稿
type historyContribution struct {
	historyContributionDo historyContributionDo

	ALL            field.Asterisk
	ID             field.Uint64
	EntryID        field.Uint64 // 为空时表示新词条投稿
	Title          field.String
	SectionName    field.String
	Content        field.String
	SourceNote     field.String
	ChangeNote     field.String
	Status         field.String // draft / pending / returned / approved / rejected
	DataDomainID   field.Uint64 // 由服务端根据投稿校友档案写入
	AuthorUserID   field.Uint64
	AuthorAlumniID field.Uint64
	ReviewedBy     field.Uint64
	ReviewComment  field.String
	SubmittedAt    field.Time
	ReviewedAt     field.Time
	CreatedAt      field.Time
	UpdatedAt      field.Time
	DeletedAt      field.Field

	fieldMap map[string]field.Expr
}

func (h historyContribution) Table(newTableName string) *historyContribution {
	h.historyContributionDo.UseTable(newTableName)
	return h.updateTableName(newTableName)
}

func (h historyContribution) As(alias string) *historyContribution {
	h.historyContributionDo.DO = *(h.historyContributionDo.As(alias).(*gen.DO))
	return h.updateTableName(alias)
}

func (h *historyContribution) updateTableName(table string) *historyContribution {
	h.ALL = field.NewAsterisk(table)
	h.ID = field.NewUint64(table, "id")
	h.EntryID = field.NewUint64(table, "entry_id")
	h.Title = field.NewString(table, "title")
	h.SectionName = field.NewString(table, "section_name")
	h.Content = field.NewString(table, "content")
	h.SourceNote = field.NewString(table, "source_note")
	h.ChangeNote = field.NewString(table, "change_note")
	h.Status = field.NewString(table, "status")
	h.DataDomainID = field.NewUint64(table, "data_domain_id")
	h.AuthorUserID = field.NewUint64(table, "author_user_id")
	h.AuthorAlumniID = field.NewUint64(table, "author_alumni_id")
	h.ReviewedBy = field.NewUint64(table, "reviewed_by")
	h.ReviewComment = field.NewString(table, "review_comment")
	h.SubmittedAt = field.NewTime(table, "submitted_at")
	h.ReviewedAt = field.NewTime(table, "reviewed_at")
	h.CreatedAt = field.NewTime(table, "created_at")
	h.UpdatedAt = field.NewTime(table, "updated_at")
	h.DeletedAt = field.NewField(table, "deleted_at")

	h.fillFieldMap()

	return h
}

func (h *historyContribution) WithContext(ctx context.Context) *historyContributionDo {
	return h.historyContributionDo.WithContext(ctx)
}

func (h historyContribution) TableName() string { return h.historyContributionDo.TableName() }

func (h historyContribution) Alias() string { return h.historyContributionDo.Alias() }

func (h historyContribution) Columns(cols ...field.Expr) gen.Columns {
	return h.historyContributionDo.Columns(cols...)
}

func (h *historyContribution) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := h.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (h *historyContribution) fillFieldMap() {
	h.fieldMap = make(map[string]field.Expr, 18)
	h.fieldMap["id"] = h.ID
	h.fieldMap["entry_id"] = h.EntryID
	h.fieldMap["title"] = h.Title
	h.fieldMap["section_name"] = h.SectionName
	h.fieldMap["content"] = h.Content
	h.fieldMap["source_note"] = h.SourceNote
	h.fieldMap["change_note"] = h.ChangeNote
	h.fieldMap["status"] = h.Status
	h.fieldMap["data_domain_id"] = h.DataDomainID
	h.fieldMap["author_user_id"] = h.AuthorUserID
	h.fieldMap["author_alumni_id"] = h.AuthorAlumniID
	h.fieldMap["reviewed_by"] = h.ReviewedBy
	h.fieldMap["review_comment"] = h.ReviewComment
	h.fieldMap["submitted_at"] = h.SubmittedAt
	h.fieldMap["reviewed_at"] = h.ReviewedAt
	h.fieldMap["created_at"] = h.CreatedAt
	h.fieldMap["updated_at"] = h.UpdatedAt
	h.fieldMap["deleted_at"] = h.DeletedAt
}

func (h historyContribution) clone(db *gorm.DB) historyContribution {
	h.historyContributionDo.ReplaceConnPool(db.Statement.ConnPool)
	return h
}

func (h historyContribution) replaceDB(db *gorm.DB) historyContribution {
	h.historyContributionDo.ReplaceDB(db)
	return h
}

type historyContributionDo struct{ gen.DO }

func (h historyContributionDo) Debug() *historyContributionDo {
	return h.withDO(h.DO.Debug())
}

func (h historyContributionDo) WithContext(ctx context.Context) *historyContributionDo {
	return h.withDO(h.DO.WithContext(ctx))
}

func (h historyContributionDo) ReadDB() *historyContributionDo {
	return h.Clauses(dbresolver.Read)
}

func (h historyContributionDo) WriteDB() *historyContributionDo {
	return h.Clauses(dbresolver.Write)
}

func (h historyContributionDo) Session(config *gorm.Session) *historyContributionDo {
	return h.withDO(h.DO.Session(config))
}

func (h historyContributionDo) Clauses(conds ...clause.Expression) *historyContributionDo {
	return h.withDO(h.DO.Clauses(conds...))
}

func (h historyContributionDo) Returning(value interface{}, columns ...string) *historyContributionDo {
	return h.withDO(h.DO.Returning(value, columns...))
}

func (h historyContributionDo) Not(conds ...gen.Condition) *historyContributionDo {
	return h.withDO(h.DO.Not(conds...))
}

func (h historyContributionDo) Or(conds ...gen.Condition) *historyContributionDo {
	return h.withDO(h.DO.Or(conds...))
}

func (h historyContributionDo) Select(conds ...field.Expr) *historyContributionDo {
	return h.withDO(h.DO.Select(conds...))
}

func (h historyContributionDo) Where(conds ...gen.Condition) *historyContributionDo {
	return h.withDO(h.DO.Where(conds...))
}

func (h historyContributionDo) Order(conds ...field.Expr) *historyContributionDo {
	return h.withDO(h.DO.Order(conds...))
}

func (h historyContributionDo) Distinct(cols ...field.Expr) *historyContributionDo {
	return h.withDO(h.DO.Distinct(cols...))
}

func (h historyContributionDo) Omit(cols ...field.Expr) *historyContributionDo {
	return h.withDO(h.DO.Omit(cols...))
}

func (h historyContributionDo) Join(table schema.Tabler, on ...field.Expr) *historyContributionDo {
	return h.withDO(h.DO.Join(table, on...))
}

func (h historyContributionDo) LeftJoin(table schema.Tabler, on ...field.Expr) *historyContributionDo {
	return h.withDO(h.DO.LeftJoin(table, on...))
}

func (h historyContributionDo) RightJoin(table schema.Tabler, on ...field.Expr) *historyContributionDo {
	return h.withDO(h.DO.RightJoin(table, on...))
}

func (h historyContributionDo) Group(cols ...field.Expr) *historyContributionDo {
	return h.withDO(h.DO.Group(cols...))
}

func (h historyContributionDo) Having(conds ...gen.Condition) *historyContributionDo {
	return h.withDO(h.DO.Having(conds...))
}

func (h historyContributionDo) Limit(limit int) *historyContributionDo {
	return h.withDO(h.DO.Limit(limit))
}

func (h historyContributionDo) Offset(offset int) *historyContributionDo {
	return h.withDO(h.DO.Offset(offset))
}

func (h historyContributionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *historyContributionDo {
	return h.withDO(h.DO.Scopes(funcs...))
}

func (h historyContributionDo) Unscoped() *historyContributionDo {
	return h.withDO(h.DO.Unscoped())
}

func (h historyContributionDo) Create(values ...*model.HistoryContribution) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Create(values)
}

func (h historyContributionDo) CreateInBatches(values []*model.HistoryContribution, batchSize int) error {
	return h.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (h historyContributionDo) Save(values ...*model.HistoryContribution) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Save(values)
}

func (h historyContributionDo) First() (*model.HistoryContribution, error) {
	if result, err := h.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.HistoryContribution), nil
	}
}

func (h historyContributionDo) Take() (*model.HistoryContribution, error) {
	if result, err := h.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.HistoryContribution), nil
	}
}

func (h historyContributionDo) Last() (*model.HistoryContribution, error) {
	if result, err := h.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.HistoryContribution), nil
	}
}

func (h historyContributionDo) Find() ([]*model.HistoryContribution, error) {
	result, err := h.DO.Find()
	return result.([]*model.HistoryContribution), err
}

func (h historyContributionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.HistoryContribution, err error) {
	buf := make([]*model.HistoryContribution, 0, batchSize)
	err = h.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (h historyContributionDo) FindInBatches(result *[]*model.HistoryContribution, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return h.DO.FindInBatches(result, batchSize, fc)
}

func (h historyContributionDo) Attrs(attrs ...field.AssignExpr) *historyContributionDo {
	return h.withDO(h.DO.Attrs(attrs...))
}

func (h historyContributionDo) Assign(attrs ...field.AssignExpr) *historyContributionDo {
	return h.withDO(h.DO.Assign(attrs...))
}

func (h historyContributionDo) Joins(fields ...field.RelationField) *historyContributionDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Joins(_f))
	}
	return &h
}

func (h historyContributionDo) Preload(fields ...field.RelationField) *historyContributionDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Preload(_f))
	}
	return &h
}

func (h historyContributionDo) FirstOrInit() (*model.HistoryContribution, error) {
	if result, err := h.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.HistoryContribution), nil
	}
}

func (h historyContributionDo) FirstOrCreate() (*model.HistoryContribution, error) {
	if result, err := h.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.HistoryContribution), nil
	}
}

func (h historyContributionDo) FindByPage(offset int, limit int) (result []*model.HistoryContribution, count int64, err error) {
	result, err = h.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = h.Offset(-1).Limit(-1).Count()
	return
}

func (h historyContributionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = h.Count()
	if err != nil {
		return
	}

	err = h.Offset(offset).Limit(limit).Scan(result)
	return
}

func (h historyContributionDo) Scan(result interface{}) (err error) {
	return h.DO.Scan(result)
}

func (h historyContributionDo) Delete(models ...*model.HistoryContribution) (result gen.ResultInfo, err error) {
	return h.DO.Delete(models)
}

func (h *historyContributionDo) withDO(do gen.Dao) *historyContributionDo {
	h.DO = *do.(*gen.DO)
	return h
}
