// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/JunLang-7/sduzg-alumin-platform/server/internal/model"
)

func newHistoryAttachment(db *gorm.DB, opts ...gen.DOOption) historyAttachment {
	_historyAttachment := historyAttachment{}

	_historyAttachment.historyAttachmentDo.UseDB(db, opts...)
	_historyAttachment.historyAttachmentDo.UseModel(&model.HistoryAttachment{})

	tableName := _historyAttachment.historyAttachmentDo.TableName()
	_historyAttachment.ALL = field.NewAsterisk(tableName)
	_historyAttachment.ID = field.NewUint64(tableName, "id")
	_historyAttachment.ContributionID = field.NewUint64(tableName, "contribution_id")
	_historyAttachment.ObjectKey = field.NewString(tableName, "object_key")
	_historyAttachment.OriginalName = field.NewString(tableName, "original_name")
	_historyAttachment.MimeType = field.NewString(tableName, "mime_type")
	_historyAttachment.FileSize = field.NewUint64(tableName, "file_size")
	_historyAttachment.Description = field.NewString(tableName, "description")
	_historyAttachment.SourceNote = field.NewString(tableName, "source_note")
	_historyAttachment.RightsNote = field.NewString(tableName, "rights_note")
	_historyAttachment.ConsentConfirmed = field.NewBool(tableName, "consent_confirmed")
	_historyAttachment.Status = field.NewString(tableName, "status")
	_historyAttachment.CreatedAt = field.NewTime(tableName, "created_at")
	_historyAttachment.UpdatedAt = field.NewTime(tableName, "updated_at")
	_historyAttachment.DeletedAt = field.NewField(tableName, "deleted_at")

	_historyAttachment.fillFieldMap()

	return _historyAttachment
}

// historyAttachment 院史投稿附件
type historyAttachment struct {
	historyAttachmentDo historyAttachmentDo

	ALL              field.Asterisk
	ID               field.Uint64
	ContributionID   field.Uint64
	ObjectKey        field.String
	OriginalName     field.String
	MimeType         field.String
	FileSize         field.Uint64
	Description      field.String
	SourceNote       field.String
	RightsNote       field.String
	ConsentConfirmed field.Bool
	Status           field.String // pending / approved / rejected
	CreatedAt        field.Time
	UpdatedAt        field.Time
	DeletedAt        field.Field

	fieldMap map[string]field.Expr
}

func (h historyAttachment) Table(newTableName string) *historyAttachment {
	h.historyAttachmentDo.UseTable(newTableName)
	return h.updateTableName(newTableName)
}

func (h historyAttachment) As(alias string) *historyAttachment {
	h.historyAttachmentDo.DO = *(h.historyAttachmentDo.As(alias).(*gen.DO))
	return h.updateTableName(alias)
}

func (h *historyAttachment) updateTableName(table string) *historyAttachment {
	h.ALL = field.NewAsterisk(table)
	h.ID = field.NewUint64(table, "id")
	h.ContributionID = field.NewUint64(table, "contribution_id")
	h.ObjectKey = field.NewString(table, "object_key")
	h.OriginalName = field.NewString(table, "original_name")
	h.MimeType = field.NewString(table, "mime_type")
	h.FileSize = field.NewUint64(table, "file_size")
	h.Description = field.NewString(table, "description")
	h.SourceNote = field.NewString(table, "source_note")
	h.RightsNote = field.NewString(table, "rights_note")
	h.ConsentConfirmed = field.NewBool(table, "consent_confirmed")
	h.Status = field.NewString(table, "status")
	h.CreatedAt = field.NewTime(table, "created_at")
	h.UpdatedAt = field.NewTime(table, "updated_at")
	h.DeletedAt = field.NewField(table, "deleted_at")

	h.fillFieldMap()

	return h
}

func (h *historyAttachment) WithContext(ctx context.Context) *historyAttachmentDo {
	return h.historyAttachmentDo.WithContext(ctx)
}

func (h historyAttachment) TableName() string { return h.historyAttachmentDo.TableName() }

func (h historyAttachment) Alias() string { return h.historyAttachmentDo.Alias() }

func (h historyAttachment) Columns(cols ...field.Expr) gen.Columns {
	return h.historyAttachmentDo.Columns(cols...)
}

func (h *historyAttachment) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := h.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (h *historyAttachment) fillFieldMap() {
	h.fieldMap = make(map[string]field.Expr, 14)
	h.fieldMap["id"] = h.ID
	h.fieldMap["contribution_id"] = h.ContributionID
	h.fieldMap["object_key"] = h.ObjectKey
	h.fieldMap["original_name"] = h.OriginalName
	h.fieldMap["mime_type"] = h.MimeType
	h.fieldMap["file_size"] = h.FileSize
	h.fieldMap["description"] = h.Description
	h.fieldMap["source_note"] = h.SourceNote
	h.fieldMap["rights_note"] = h.RightsNote
	h.fieldMap["consent_confirmed"] = h.ConsentConfirmed
	h.fieldMap["status"] = h.Status
	h.fieldMap["created_at"] = h.CreatedAt
	h.fieldMap["updated_at"] = h.UpdatedAt
	h.fieldMap["deleted_at"] = h.DeletedAt
}

func (h historyAttachment) clone(db *gorm.DB) historyAttachment {
	h.historyAttachmentDo.ReplaceConnPool(db.Statement.ConnPool)
	return h
}

func (h historyAttachment) replaceDB(db *gorm.DB) historyAttachment {
	h.historyAttachmentDo.ReplaceDB(db)
	return h
}

type historyAttachmentDo struct{ gen.DO }

func (h historyAttachmentDo) Debug() *historyAttachmentDo {
	return h.withDO(h.DO.Debug())
}

func (h historyAttachmentDo) WithContext(ctx context.Context) *historyAttachmentDo {
	return h.withDO(h.DO.WithContext(ctx))
}

func (h historyAttachmentDo) ReadDB() *historyAttachmentDo {
	return h.Clauses(dbresolver.Read)
}

func (h historyAttachmentDo) WriteDB() *historyAttachmentDo {
	return h.Clauses(dbresolver.Write)
}

func (h historyAttachmentDo) Session(config *gorm.Session) *historyAttachmentDo {
	return h.withDO(h.DO.Session(config))
}

func (h historyAttachmentDo) Clauses(conds ...clause.Expression) *historyAttachmentDo {
	return h.withDO(h.DO.Clauses(conds...))
}

func (h historyAttachmentDo) Returning(value interface{}, columns ...string) *historyAttachmentDo {
	return h.withDO(h.DO.Returning(value, columns...))
}

func (h historyAttachmentDo) Not(conds ...gen.Condition) *historyAttachmentDo {
	return h.withDO(h.DO.Not(conds...))
}

func (h historyAttachmentDo) Or(conds ...gen.Condition) *historyAttachmentDo {
	return h.withDO(h.DO.Or(conds...))
}

func (h historyAttachmentDo) Select(conds ...field.Expr) *historyAttachmentDo {
	return h.withDO(h.DO.Select(conds...))
}

func (h historyAttachmentDo) Where(conds ...gen.Condition) *historyAttachmentDo {
	return h.withDO(h.DO.Where(conds...))
}

func (h historyAttachmentDo) Order(conds ...field.Expr) *historyAttachmentDo {
	return h.withDO(h.DO.Order(conds...))
}

func (h historyAttachmentDo) Distinct(cols ...field.Expr) *historyAttachmentDo {
	return h.withDO(h.DO.Distinct(cols...))
}

func (h historyAttachmentDo) Omit(cols ...field.Expr) *historyAttachmentDo {
	return h.withDO(h.DO.Omit(cols...))
}

func (h historyAttachmentDo) Join(table schema.Tabler, on ...field.Expr) *historyAttachmentDo {
	return h.withDO(h.DO.Join(table, on...))
}

func (h historyAttachmentDo) LeftJoin(table schema.Tabler, on ...field.Expr) *historyAttachmentDo {
	return h.withDO(h.DO.LeftJoin(table, on...))
}

func (h historyAttachmentDo) RightJoin(table schema.Tabler, on ...field.Expr) *historyAttachmentDo {
	return h.withDO(h.DO.RightJoin(table, on...))
}

func (h historyAttachmentDo) Group(cols ...field.Expr) *historyAttachmentDo {
	return h.withDO(h.DO.Group(cols...))
}

func (h historyAttachmentDo) Having(conds ...gen.Condition) *historyAttachmentDo {
	return h.withDO(h.DO.Having(conds...))
}

func (h historyAttachmentDo) Limit(limit int) *historyAttachmentDo {
	return h.withDO(h.DO.Limit(limit))
}

func (h historyAttachmentDo) Offset(offset int) *historyAttachmentDo {
	return h.withDO(h.DO.Offset(offset))
}

func (h historyAttachmentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *historyAttachmentDo {
	return h.withDO(h.DO.Scopes(funcs...))
}

func (h historyAttachmentDo) Unscoped() *historyAttachmentDo {
	return h.withDO(h.DO.Unscoped())
}

func (h historyAttachmentDo) Create(values ...*model.HistoryAttachment) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Create(values)
}

func (h historyAttachmentDo) CreateInBatches(values []*model.HistoryAttachment, batchSize int) error {
	return h.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (h historyAttachmentDo) Save(values ...*model.HistoryAttachment) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Save(values)
}

func (h historyAttachmentDo) First() (*model.HistoryAttachment, error) {
	if result, err := h.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.HistoryAttachment), nil
	}
}

func (h historyAttachmentDo) Take() (*model.HistoryAttachment, error) {
	if result, err := h.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.HistoryAttachment), nil
	}
}

func (h historyAttachmentDo) Last() (*model.HistoryAttachment, error) {
	if result, err := h.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.HistoryAttachment), nil
	}
}

func (h historyAttachmentDo) Find() ([]*model.HistoryAttachment, error) {
	result, err := h.DO.Find()
	return result.([]*model.HistoryAttachment), err
}

func (h historyAttachmentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.HistoryAttachment, err error) {
	buf := make([]*model.HistoryAttachment, 0, batchSize)
	err = h.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (h historyAttachmentDo) FindInBatches(result *[]*model.HistoryAttachment, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return h.DO.FindInBatches(result, batchSize, fc)
}

func (h historyAttachmentDo) Attrs(attrs ...field.AssignExpr) *historyAttachmentDo {
	return h.withDO(h.DO.Attrs(attrs...))
}

func (h historyAttachmentDo) Assign(attrs ...field.AssignExpr) *historyAttachmentDo {
	return h.withDO(h.DO.Assign(attrs...))
}

func (h historyAttachmentDo) Joins(fields ...field.RelationField) *historyAttachmentDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Joins(_f))
	}
	return &h
}

func (h historyAttachmentDo) Preload(fields ...field.RelationField) *historyAttachmentDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Preload(_f))
	}
	return &h
}

func (h historyAttachmentDo) FirstOrInit() (*model.HistoryAttachment, error) {
	if result, err := h.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.HistoryAttachment), nil
	}
}

func (h historyAttachmentDo) FirstOrCreate() (*model.HistoryAttachment, error) {
	if result, err := h.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.HistoryAttachment), nil
	}
}

func (h historyAttachmentDo) FindByPage(offset int, limit int) (result []*model.HistoryAttachment, count int64, err error) {
	result, err = h.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = h.Offset(-1).Limit(-1).Count()
	return
}

func (h historyAttachmentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = h.Count()
	if err != nil {
		return
	}

	err = h.Offset(offset).Limit(limit).Scan(result)
	return
}

func (h historyAttachmentDo) Scan(result interface{}) (err error) {
	return h.DO.Scan(result)
}

func (h historyAttachmentDo) Delete(models ...*model.HistoryAttachment) (result gen.ResultInfo, err error) {
	return h.DO.Delete(models)
}

func (h *historyAttachmentDo) withDO(do gen.Dao) *historyAttachmentDo {
	h.DO = *do.(*gen.DO)
	return h
}
