// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/JunLang-7/sduzg-alumin-platform/server/internal/model"
)

func newHistoryEntryVersion(db *gorm.DB, opts ...gen.DOOption) historyEntryVersion {
	_historyEntryVersion := historyEntryVersion{}

	_historyEntryVersion.historyEntryVersionDo.UseDB(db, opts...)
	_historyEntryVersion.historyEntryVersionDo.UseModel(&model.HistoryEntryVersion{})

	tableName := _historyEntryVersion.historyEntryVersionDo.TableName()
	_historyEntryVersion.ALL = field.NewAsterisk(tableName)
	_historyEntryVersion.ID = field.NewUint64(tableName, "id")
	_historyEntryVersion.EntryID = field.NewUint64(tableName, "entry_id")
	_historyEntryVersion.VersionNumber = field.NewUint32(tableName, "version_number")
	_historyEntryVersion.Title = field.NewString(tableName, "title")
	_historyEntryVersion.Summary = field.NewString(tableName, "summary")
	_historyEntryVersion.Content = field.NewString(tableName, "content")
	_historyEntryVersion.SourceNote = field.NewString(tableName, "source_note")
	_historyEntryVersion.ContributionID = field.NewUint64(tableName, "contribution_id")
	_historyEntryVersion.ApprovedBy = field.NewUint64(tableName, "approved_by")
	_historyEntryVersion.CreatedAt = field.NewTime(tableName, "created_at")

	_historyEntryVersion.fillFieldMap()

	return _historyEntryVersion
}

// historyEntryVersion ????????????
type historyEntryVersion struct {
	historyEntryVersionDo historyEntryVersionDo

	ALL            field.Asterisk
	ID             field.Uint64
	EntryID        field.Uint64
	VersionNumber  field.Uint32
	Title          field.String
	Summary        field.String
	Content        field.String
	SourceNote     field.String
	ContributionID field.Uint64
	ApprovedBy     field.Uint64
	CreatedAt      field.Time

	fieldMap map[string]field.Expr
}

func (h historyEntryVersion) Table(newTableName string) *historyEntryVersion {
	h.historyEntryVersionDo.UseTable(newTableName)
	return h.updateTableName(newTableName)
}

func (h historyEntryVersion) As(alias string) *historyEntryVersion {
	h.historyEntryVersionDo.DO = *(h.historyEntryVersionDo.As(alias).(*gen.DO))
	return h.updateTableName(alias)
}

func (h *historyEntryVersion) updateTableName(table string) *historyEntryVersion {
	h.ALL = field.NewAsterisk(table)
	h.ID = field.NewUint64(table, "id")
	h.EntryID = field.NewUint64(table, "entry_id")
	h.VersionNumber = field.NewUint32(table, "version_number")
	h.Title = field.NewString(table, "title")
	h.Summary = field.NewString(table, "summary")
	h.Content = field.NewString(table, "content")
	h.SourceNote = field.NewString(table, "source_note")
	h.ContributionID = field.NewUint64(table, "contribution_id")
	h.ApprovedBy = field.NewUint64(table, "approved_by")
	h.CreatedAt = field.NewTime(table, "created_at")

	h.fillFieldMap()

	return h
}

func (h *historyEntryVersion) WithContext(ctx context.Context) *historyEntryVersionDo {
	return h.historyEntryVersionDo.WithContext(ctx)
}

func (h historyEntryVersion) TableName() string { return h.historyEntryVersionDo.TableName() }

func (h historyEntryVersion) Alias() string { return h.historyEntryVersionDo.Alias() }

func (h historyEntryVersion) Columns(cols ...field.Expr) gen.Columns {
	return h.historyEntryVersionDo.Columns(cols...)
}

func (h *historyEntryVersion) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := h.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (h *historyEntryVersion) fillFieldMap() {
	h.fieldMap = make(map[string]field.Expr, 10)
	h.fieldMap["id"] = h.ID
	h.fieldMap["entry_id"] = h.EntryID
	h.fieldMap["version_number"] = h.VersionNumber
	h.fieldMap["title"] = h.Title
	h.fieldMap["summary"] = h.Summary
	h.fieldMap["content"] = h.Content
	h.fieldMap["source_note"] = h.SourceNote
	h.fieldMap["contribution_id"] = h.ContributionID
	h.fieldMap["approved_by"] = h.ApprovedBy
	h.fieldMap["created_at"] = h.CreatedAt
}

func (h historyEntryVersion) clone(db *gorm.DB) historyEntryVersion {
	h.historyEntryVersionDo.ReplaceConnPool(db.Statement.ConnPool)
	return h
}

func (h historyEntryVersion) replaceDB(db *gorm.DB) historyEntryVersion {
	h.historyEntryVersionDo.ReplaceDB(db)
	return h
}

type historyEntryVersionDo struct{ gen.DO }

func (h historyEntryVersionDo) Debug() *historyEntryVersionDo {
	return h.withDO(h.DO.Debug())
}

func (h historyEntryVersionDo) WithContext(ctx context.Context) *historyEntryVersionDo {
	return h.withDO(h.DO.WithContext(ctx))
}

func (h historyEntryVersionDo) ReadDB() *historyEntryVersionDo {
	return h.Clauses(dbresolver.Read)
}

func (h historyEntryVersionDo) WriteDB() *historyEntryVersionDo {
	return h.Clauses(dbresolver.Write)
}

func (h historyEntryVersionDo) Session(config *gorm.Session) *historyEntryVersionDo {
	return h.withDO(h.DO.Session(config))
}

func (h historyEntryVersionDo) Clauses(conds ...clause.Expression) *historyEntryVersionDo {
	return h.withDO(h.DO.Clauses(conds...))
}

func (h historyEntryVersionDo) Returning(value interface{}, columns ...string) *historyEntryVersionDo {
	return h.withDO(h.DO.Returning(value, columns...))
}

func (h historyEntryVersionDo) Not(conds ...gen.Condition) *historyEntryVersionDo {
	return h.withDO(h.DO.Not(conds...))
}

func (h historyEntryVersionDo) Or(conds ...gen.Condition) *historyEntryVersionDo {
	return h.withDO(h.DO.Or(conds...))
}

func (h historyEntryVersionDo) Select(conds ...field.Expr) *historyEntryVersionDo {
	return h.withDO(h.DO.Select(conds...))
}

func (h historyEntryVersionDo) Where(conds ...gen.Condition) *historyEntryVersionDo {
	return h.withDO(h.DO.Where(conds...))
}

func (h historyEntryVersionDo) Order(conds ...field.Expr) *historyEntryVersionDo {
	return h.withDO(h.DO.Order(conds...))
}

func (h historyEntryVersionDo) Distinct(cols ...field.Expr) *historyEntryVersionDo {
	return h.withDO(h.DO.Distinct(cols...))
}

func (h historyEntryVersionDo) Omit(cols ...field.Expr) *historyEntryVersionDo {
	return h.withDO(h.DO.Omit(cols...))
}

func (h historyEntryVersionDo) Join(table schema.Tabler, on ...field.Expr) *historyEntryVersionDo {
	return h.withDO(h.DO.Join(table, on...))
}

func (h historyEntryVersionDo) LeftJoin(table schema.Tabler, on ...field.Expr) *historyEntryVersionDo {
	return h.withDO(h.DO.LeftJoin(table, on...))
}

func (h historyEntryVersionDo) RightJoin(table schema.Tabler, on ...field.Expr) *historyEntryVersionDo {
	return h.withDO(h.DO.RightJoin(table, on...))
}

func (h historyEntryVersionDo) Group(cols ...field.Expr) *historyEntryVersionDo {
	return h.withDO(h.DO.Group(cols...))
}

func (h historyEntryVersionDo) Having(conds ...gen.Condition) *historyEntryVersionDo {
	return h.withDO(h.DO.Having(conds...))
}

func (h historyEntryVersionDo) Limit(limit int) *historyEntryVersionDo {
	return h.withDO(h.DO.Limit(limit))
}

func (h historyEntryVersionDo) Offset(offset int) *historyEntryVersionDo {
	return h.withDO(h.DO.Offset(offset))
}

func (h historyEntryVersionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *historyEntryVersionDo {
	return h.withDO(h.DO.Scopes(funcs...))
}

func (h historyEntryVersionDo) Unscoped() *historyEntryVersionDo {
	return h.withDO(h.DO.Unscoped())
}

func (h historyEntryVersionDo) Create(values ...*model.HistoryEntryVersion) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Create(values)
}

func (h historyEntryVersionDo) CreateInBatches(values []*model.HistoryEntryVersion, batchSize int) error {
	return h.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (h historyEntryVersionDo) Save(values ...*model.HistoryEntryVersion) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Save(values)
}

func (h historyEntryVersionDo) First() (*model.HistoryEntryVersion, error) {
	if result, err := h.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.HistoryEntryVersion), nil
	}
}

func (h historyEntryVersionDo) Take() (*model.HistoryEntryVersion, error) {
	if result, err := h.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.HistoryEntryVersion), nil
	}
}

func (h historyEntryVersionDo) Last() (*model.HistoryEntryVersion, error) {
	if result, err := h.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.HistoryEntryVersion), nil
	}
}

func (h historyEntryVersionDo) Find() ([]*model.HistoryEntryVersion, error) {
	result, err := h.DO.Find()
	return result.([]*model.HistoryEntryVersion), err
}

func (h historyEntryVersionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.HistoryEntryVersion, err error) {
	buf := make([]*model.HistoryEntryVersion, 0, batchSize)
	err = h.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (h historyEntryVersionDo) FindInBatches(result *[]*model.HistoryEntryVersion, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return h.DO.FindInBatches(result, batchSize, fc)
}

func (h historyEntryVersionDo) Attrs(attrs ...field.AssignExpr) *historyEntryVersionDo {
	return h.withDO(h.DO.Attrs(attrs...))
}

func (h historyEntryVersionDo) Assign(attrs ...field.AssignExpr) *historyEntryVersionDo {
	return h.withDO(h.DO.Assign(attrs...))
}

func (h historyEntryVersionDo) Joins(fields ...field.RelationField) *historyEntryVersionDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Joins(_f))
	}
	return &h
}

func (h historyEntryVersionDo) Preload(fields ...field.RelationField) *historyEntryVersionDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Preload(_f))
	}
	return &h
}

func (h historyEntryVersionDo) FirstOrInit() (*model.HistoryEntryVersion, error) {
	if result, err := h.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.HistoryEntryVersion), nil
	}
}

func (h historyEntryVersionDo) FirstOrCreate() (*model.HistoryEntryVersion, error) {
	if result, err := h.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.HistoryEntryVersion), nil
	}
}

func (h historyEntryVersionDo) FindByPage(offset int, limit int) (result []*model.HistoryEntryVersion, count int64, err error) {
	result, err = h.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = h.Offset(-1).Limit(-1).Count()
	return
}

func (h historyEntryVersionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = h.Count()
	if err != nil {
		return
	}

	err = h.Offset(offset).Limit(limit).Scan(result)
	return
}

func (h historyEntryVersionDo) Scan(result interface{}) (err error) {
	return h.DO.Scan(result)
}

func (h historyEntryVersionDo) Delete(models ...*model.HistoryEntryVersion) (result gen.ResultInfo, err error) {
	return h.DO.Delete(models)
}

func (h *historyEntryVersionDo) withDO(do gen.Dao) *historyEntryVersionDo {
	h.DO = *do.(*gen.DO)
	return h
}
