// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameHistoryEntryVersion = "history_entry_versions"

// HistoryEntryVersion ????????????
type HistoryEntryVersion struct {
	ID             uint64    `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	EntryID        uint64    `gorm:"column:entry_id;type:bigint unsigned;not null;uniqueIndex:uk_history_entry_version,priority:1;index:idx_history_versions_entry_created,priority:1" json:"entry_id"`
	VersionNumber  uint32    `gorm:"column:version_number;type:int unsigned;not null;uniqueIndex:uk_history_entry_version,priority:2" json:"version_number"`
	Title          string    `gorm:"column:title;type:varchar(200);not null" json:"title"`
	Summary        string    `gorm:"column:summary;type:varchar(1000);not null" json:"summary"`
	Content        string    `gorm:"column:content;type:mediumtext;not null" json:"content"`
	SourceNote     string    `gorm:"column:source_note;type:text;not null" json:"source_note"`
	ContributionID *uint64   `gorm:"column:contribution_id;type:bigint unsigned" json:"contribution_id"`
	ApprovedBy     uint64    `gorm:"column:approved_by;type:bigint unsigned;not null" json:"approved_by"`
	CreatedAt      time.Time `gorm:"column:created_at;type:datetime;not null;index:idx_history_versions_entry_created,priority:2;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName HistoryEntryVersion's table name
func (*HistoryEntryVersion) TableName() string {
	return TableNameHistoryEntryVersion
}
