// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameHistoryContribution = "history_contributions"

// HistoryContribution 院史校友投稿
type HistoryContribution struct {
	ID             uint64         `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	EntryID        *uint64        `gorm:"column:entry_id;type:bigint unsigned;index:idx_history_contrib_entry,priority:1;comment:为空时表示新词条投稿" json:"entry_id"` // 为空时表示新词条投稿
	Title          string         `gorm:"column:title;type:varchar(200);not null" json:"title"`
	SectionName    string         `gorm:"column:section_name;type:varchar(100);not null" json:"section_name"`
	Content        string         `gorm:"column:content;type:mediumtext;not null" json:"content"`
	SourceNote     string         `gorm:"column:source_note;type:text;not null" json:"source_note"`
	ChangeNote     string         `gorm:"column:change_note;type:varchar(1000);not null" json:"change_note"`
	Status         string         `gorm:"column:status;type:varchar(32);not null;index:idx_history_contrib_author_status,priority:2;index:idx_history_contrib_domain_status,priority:2;default:draft;comment:draft / pending / returned / approved / rejected" json:"status"` // draft / pending / returned / approved / rejected
	DataDomainID   *uint64        `gorm:"column:data_domain_id;type:bigint unsigned;index:idx_history_contrib_domain_status,priority:1;comment:由服务端根据投稿校友档案写入" json:"data_domain_id"`                                                                                         // 由服务端根据投稿校友档案写入
	AuthorUserID   uint64         `gorm:"column:author_user_id;type:bigint unsigned;not null;index:idx_history_contrib_author_status,priority:1" json:"author_user_id"`
	AuthorAlumniID uint64         `gorm:"column:author_alumni_id;type:bigint unsigned;not null" json:"author_alumni_id"`
	ReviewedBy     *uint64        `gorm:"column:reviewed_by;type:bigint unsigned" json:"reviewed_by"`
	ReviewComment  *string        `gorm:"column:review_comment;type:text" json:"review_comment"`
	SubmittedAt    *time.Time     `gorm:"column:submitted_at;type:datetime;index:idx_history_contrib_domain_status,priority:3" json:"submitted_at"`
	ReviewedAt     *time.Time     `gorm:"column:reviewed_at;type:datetime" json:"reviewed_at"`
	CreatedAt      time.Time      `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt      time.Time      `gorm:"column:updated_at;type:datetime;not null;index:idx_history_contrib_author_status,priority:3;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt      gorm.DeletedAt `gorm:"column:deleted_at;type:datetime" json:"deleted_at"`
}

// TableName HistoryContribution's table name
func (*HistoryContribution) TableName() string {
	return TableNameHistoryContribution
}
