// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameHistoryEntry = "history_entries"

// HistoryEntry ?????????
type HistoryEntry struct {
	ID             uint64         `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	Title          string         `gorm:"column:title;type:varchar(200);not null;uniqueIndex:uk_history_entries_title,priority:1" json:"title"`
	Summary        string         `gorm:"column:summary;type:varchar(1000);not null" json:"summary"`
	Content        string         `gorm:"column:content;type:mediumtext;not null" json:"content"`
	Status         string         `gorm:"column:status;type:varchar(32);not null;index:idx_history_entries_status_updated,priority:1;default:published;comment:published / archived" json:"status"` // published / archived
	CurrentVersion uint32         `gorm:"column:current_version;type:int unsigned;not null;default:1" json:"current_version"`
	CreatedBy      *uint64        `gorm:"column:created_by;type:bigint unsigned" json:"created_by"`
	UpdatedBy      *uint64        `gorm:"column:updated_by;type:bigint unsigned" json:"updated_by"`
	CreatedAt      time.Time      `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt      time.Time      `gorm:"column:updated_at;type:datetime;not null;index:idx_history_entries_status_updated,priority:2;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt      gorm.DeletedAt `gorm:"column:deleted_at;type:datetime" json:"deleted_at"`
}

// TableName HistoryEntry's table name
func (*HistoryEntry) TableName() string {
	return TableNameHistoryEntry
}
