// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameHistoryAttachment = "history_attachments"

// HistoryAttachment 院史投稿附件
type HistoryAttachment struct {
	ID               uint64         `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	ContributionID   uint64         `gorm:"column:contribution_id;type:bigint unsigned;not null;index:idx_history_attachments_contribution,priority:1" json:"contribution_id"`
	ObjectKey        string         `gorm:"column:object_key;type:varchar(512);not null" json:"object_key"`
	OriginalName     string         `gorm:"column:original_name;type:varchar(255);not null" json:"original_name"`
	MimeType         string         `gorm:"column:mime_type;type:varchar(128);not null" json:"mime_type"`
	FileSize         uint64         `gorm:"column:file_size;type:bigint unsigned;not null" json:"file_size"`
	Description      string         `gorm:"column:description;type:varchar(1000);not null" json:"description"`
	SourceNote       string         `gorm:"column:source_note;type:text;not null" json:"source_note"`
	RightsNote       string         `gorm:"column:rights_note;type:text;not null" json:"rights_note"`
	ConsentConfirmed bool           `gorm:"column:consent_confirmed;type:tinyint(1);not null" json:"consent_confirmed"`
	Status           string         `gorm:"column:status;type:varchar(32);not null;index:idx_history_attachments_contribution,priority:2;default:pending;comment:pending / approved / rejected" json:"status"` // pending / approved / rejected
	CreatedAt        time.Time      `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt        time.Time      `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt        gorm.DeletedAt `gorm:"column:deleted_at;type:datetime" json:"deleted_at"`
}

// TableName HistoryAttachment's table name
func (*HistoryAttachment) TableName() string {
	return TableNameHistoryAttachment
}
